### ISSUE TITLE
pre save?

### ISSUE THREAD

**Issue by jspizziri** [CentralPing/mongoose-plugin-created#1]
I installed this plugin, however it doesn't look like it's being called on the pre save hook.

**Comment by JasonCust** [comment]
@jspizziri I'll take a look tonight to see if I can reproduce the same issue.

**Comment by JasonCust** [comment]
@jspizziri I have not been able to reproduce this. Can you provide sample code that shows this issue?

**Comment by jspizziri** [comment]
I just added the plugin to my model, when the model was created, it didn't add a createdAt to the document. 

Then I looked through the code and I didn't see where it did anything on the pre:save hook.

**Comment by JasonCust** [comment]
@jspizziri By default (unless any options are specified), the date field will be a virtual path. So if you are looking at the stored document (or the object without virtual paths) you won't see the field. This is easily changed by setting the `date.useVirtual` option to false. Does that resolve the issue for you?
